# Generated by Django 4.2.6 on 2024-05-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(auto_now_add=True)),
                ('match_location', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=15)),
                ('player_age', models.PositiveSmallIntegerField()),
                ('player_role', models.CharField(choices=[('BT', 'Batsman'), ('B', 'Bowler'), ('AR', 'All Rounder')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('team_coach', models.CharField(max_length=10)),
                ('team_homeground', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('run', models.PositiveIntegerField()),
                ('wickets', models.PositiveIntegerField()),
                ('overs', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_team',
            field=models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team'),
        ),
    ]
