# Generated by Django 4.2.6 on 2024-05-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='match',
        ),
        migrations.RemoveField(
            model_name='score',
            name='team',
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='match_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
        migrations.AddField(
            model_name='score',
            name='match_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
        migrations.AddField(
            model_name='team',
            name='match_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
    ]
