# Generated by Django 4.2.6 on 2024-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_remove_match_match_team_remove_score_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
