# Generated by Django 4.2.6 on 2024-06-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_alter_match_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_location',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
