# Generated by Django 4.2.6 on 2024-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_alter_match_match_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(default=1, null=True, unique=True),
        ),
    ]
