# Generated by Django 4.2.6 on 2024-06-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_remove_score_score_score_team_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='match_number',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='match_number',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='match_number',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_coach',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
