# Generated by Django 4.2.6 on 2024-06-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_alter_match_match_date_alter_player_match_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_over',
            field=models.IntegerField(default=1),
        ),
    ]
