# Generated by Django 4.2.6 on 2024-06-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_match_match_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_age',
        ),
    ]
