# Generated by Django 4.2.6 on 2024-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0010_remove_player_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_toss',
            field=models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='extra_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='no_four',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='no_six',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
