# Generated by Django 4.2.6 on 2024-06-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0013_alter_match_match_toss'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_choice',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
