# Generated by Django 4.2.6 on 2024-06-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0014_team_team_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_availabel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_toss',
            field=models.CharField(choices=[('Team 1', 'Team 1'), ('Team 2', 'Team 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_choice',
            field=models.CharField(choices=[('Head', 'Head'), ('Tail', 'Tail')], max_length=4, null=True),
        ),
    ]
