# Generated by Django 4.2.6 on 2024-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0015_player_player_availabel_player_player_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(),
        ),
    ]
