# Generated by Django 4.2.6 on 2024-06-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0016_alter_player_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(null=True),
        ),
    ]
